export const translations = {
  en: {
    // Auth Page
    "login.title": "Welcome Back!",
    "login.description": "Enter your credentials to access your account",
    "signup.title": "Create an Account",
    "signup.description": "Enter your details to get started",
    "email": "Email",
    "password": "Password",
    "login.button": "Log In",
    "signup.button": "Sign Up",
    "no.account": "Don't have an account?",
    "has.account": "Already have an account?",
    "forgot.password": "Forgot Password?",
    "reset.password.title": "Reset Password",
    "reset.password.description": "Enter your email to receive a reset link.",
    "send.reset.link": "Send Reset Link",
    "back.to.login": "Back to Login",
    "password.validation.length": "At least 8 characters",
    "password.validation.uppercase": "One uppercase letter",
    "password.validation.lowercase": "One lowercase letter",
    "password.validation.number": "One number",
    "password.validation.special": "One special character",

    // Home Page & Tasks
    "header.title": "TodoApp",
    "logout": "Logout",
    "dashboard.title": "Dashboard",
    "dashboard.completed": "Completed",
    "dashboard.pending": "Pending",
    "dashboard.progress": "Tasks Progress",
    "tasks.title": "Your Tasks",
    "add.task": "Add Task",
    "search.placeholder": "Search tasks...",
    "filter.all": "All",
    "filter.completed": "Completed",
    "filter.pending": "Pending",
    "sort.by": "Sort by:",
    "sort.latest": "Latest",
    "sort.oldest": "Oldest",
    "empty.state.title": "No tasks yet!",
    "empty.state.description": "Click 'Add Task' to create your first task.",
    "task.read.more": "Read More",
    "task.read.less": "Read Less",
    "task.edit": "Edit",
    "task.delete": "Delete",
    "task.form.add.title": "Add a new task",
    "task.form.edit.title": "Edit task",
    "task.form.title.label": "Title",
    "task.form.notes.label": "Notes (Optional)",
    "task.form.save": "Save Task",
    "task.form.update": "Update Task",
    "task.delete.confirm": "Are you sure you want to delete this task?",
    
    // AI Feature
    "ai.button": "Generate Tasks from Goal",
    "ai.modal.title": "Generate Tasks with AI",
    "ai.modal.description": "Describe your goal, and we'll generate a few tasks to get you started.",
    "ai.modal.goal.placeholder": "e.g., 'Learn React in 30 days'",
    "ai.modal.generate": "Generate",
    "ai.generating": "Generating tasks...",

    // Toasts
    "toast.login.success": "Logged in successfully!",
    "toast.signup.success": "Account created successfully!",
    "toast.logout.success": "Logged out successfully.",
    "toast.reset.success": "Password reset link sent!",
    "toast.task.add.success": "Task added!",
    "toast.task.update.success": "Task updated!",
    "toast.task.delete.success": "Task deleted!",
    "toast.ai.success": "AI tasks generated!",
    "toast.error.generic": "An error occurred. Please try again.",
    "toast.error.auth": "Invalid email or password."
  },
  hi: {
    // Auth Page
    "login.title": "वापस स्वागत है!",
    "login.description": "अपने खाते तक पहुंचने के लिए अपनी साख दर्ज करें",
    "signup.title": "खाता बनाएं",
    "signup.description": "शुरू करने के लिए अपना विवरण दर्ज करें",
    "email": "ईमेल",
    "password": "पासवर्ड",
    "login.button": "लॉग इन करें",
    "signup.button": "साइन अप करें",
    "no.account": "खाता नहीं है?",
    "has.account": "पहले से ही एक खाता है?",
    "forgot.password": "पासवर्ड भूल गए?",
    "reset.password.title": "पासवर्ड रीसेट",
    "reset.password.description": "रीसेट लिंक प्राप्त करने के लिए अपना ईमेल दर्ज करें।",
    "send.reset.link": "रीसेट लिंक भेजें",
    "back.to.login": "लॉगिन पर वापस जाएं",
    "password.validation.length": "कम से कम 8 अक्षर",
    "password.validation.uppercase": "एक बड़ा अक्षर",
    "password.validation.lowercase": "एक छोटा अक्षर",
    "password.validation.number": "एक संख्या",
    "password.validation.special": "एक विशेष प्रतीक",

    // Home Page & Tasks
    "header.title": "टूडूऐप",
    "logout": "लॉग आउट",
    "dashboard.title": "डैशबोर्ड",
    "dashboard.completed": "पूर्ण",
    "dashboard.pending": "लंबित",
    "dashboard.progress": "कार्य प्रगति",
    "tasks.title": "आपके कार्य",
    "add.task": "कार्य जोड़ें",
    "search.placeholder": "कार्यों को खोजें...",
    "filter.all": "सभी",
    "filter.completed": "पूर्ण",
    "filter.pending": "लंबित",
    "sort.by": "क्रमबद्ध करें:",
    "sort.latest": "नवीनतम",
    "sort.oldest": "सबसे पुराना",
    "empty.state.title": "अभी तक कोई कार्य नहीं!",
    "empty.state.description": "अपना पहला कार्य बनाने के लिए 'कार्य जोड़ें' पर क्लिक करें।",
    "task.read.more": " और पढ़ें",
    "task.read.less": "कम पढ़ें",
    "task.edit": "संपादित करें",
    "task.delete": "हटाएं",
    "task.form.add.title": "एक नया कार्य जोड़ें",
    "task.form.edit.title": "कार्य संपादित करें",
    "task.form.title.label": "शीर्षक",
    "task.form.notes.label": "नोट्स (वैकल्पिक)",
    "task.form.save": "कार्य सहेजें",
    "task.form.update": "कार्य अपडेट करें",
    "task.delete.confirm": "क्या आप वाकई इस कार्य को हटाना चाहते हैं?",

    // AI Feature
    "ai.button": "लक्ष्य से कार्य उत्पन्न करें",
    "ai.modal.title": "AI के साथ कार्य उत्पन्न करें",
    "ai.modal.description": "अपने लक्ष्य का वर्णन करें, और हम आपको शुरू करने के लिए कुछ कार्य उत्पन्न करेंगे।",
    "ai.modal.goal.placeholder": "जैसे, '30 दिनों में रिएक्ट सीखें'",
    "ai.modal.generate": "उत्पन्न करें",
    "ai.generating": "कार्य उत्पन्न हो रहे हैं...",
    
    // Toasts
    "toast.login.success": "सफलतापूर्वक लॉग इन किया!",
    "toast.signup.success": "खाता सफलतापूर्वक बनाया गया!",
    "toast.logout.success": "सफलतापूर्वक लॉग आउट किया।",
    "toast.reset.success": "पासवर्ड रीसेट लिंक भेजा गया!",
    "toast.task.add.success": "कार्य जोड़ा गया!",
    "toast.task.update.success": "कार्य अपडेट किया गया!",
    "toast.task.delete.success": "कार्य हटा दिया गया!",
    "toast.ai.success": "AI कार्य उत्पन्न हुए!",
    "toast.error.generic": "एक त्रुटि हुई। कृपया पुन: प्रयास करें।",
    "toast.error.auth": "अमान्य ईमेल या पासवर्ड।"
  }
};
